name: 🐧 Linux Builds

on:
  workflow_dispatch:

jobs:
  build_linux_qt:
    name: "AppImage"
    uses: ./.github/workflows/linux_build_qt.yml
    with:
      jobName: "AppImage Build"
      artifactPrefixName: "PCSX2-linux-Qt-x64-appimage"
      compiler: clang
      cmakeflags: ""
      buildAppImage: true
    secrets: inherit
  build_linux_flatpak:
    name: "Flatpak"
    uses: ./.github/workflows/linux_build_flatpak.yml
    with:
      jobName: "Flatpak Build"
      artifactPrefixName: "PCSX2-linux-Qt-x64-flatpak"
      compiler: clang
      cmakeflags: ""
      publish: false
    secrets: inherit
