name: 🍎 MacOS Builds

on:
  workflow_dispatch:

jobs:
  build_macos_qt:
    name: "Defaults"
    uses: ./.github/workflows/macos_build.yml
    with:
      jobName: "MacOS Build"
      artifactPrefixName: "PCSX2-macos-Qt"
      sign_and_notarize: false
    secrets: inherit
  build_macos_qt_arm:
    name: "arm64"
    uses: ./.github/workflows/macos_build.yml
    with:
      jobName: "MacOS arm64 Build"
      artifactPrefixName: "PCSX2-macos-Qt-arm64"
      arch: arm64
    secrets: inherit
